name: img_pipe_py2
channels:
- defaults
dependencies:
- freetype=2.5.5=2
- libpng=1.6.27=0
- mkl=2017.0.3=0
- numpy=1.13.1=py27_0
- openssl=1.0.2l=0
- pip=9.0.1=py27_1
- pyqt=4.11.4=py27_4
- python=2.7.13=0
- qt=4.8.7=4
- readline=6.2=2
- scipy=0.19.1=np113py27_0
- setuptools=27.2.0=py27_0
- sip=4.18=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- vtk=6.3.0=py27_1
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - appnope==0.1.0
  - apptools==4.4.0
  - backports.shutil-get-terminal-size==1.0.0
  - configobj==5.0.6
  - configparser==3.5.0
  - cycler==0.10.0
  - cython==0.26
  - decorator==4.1.2
  - enum34==1.1.6
  - img-pipe==2017.7.12.1
  - ipython==5.4.1
  - ipython-genutils==0.2.0
  - matplotlib==1.5.3
  - mayavi==4.5.0
  - mne==0.14.1
  - mpmath==0.19
  - nibabel==2.1.0
  - nipy==0.4.1
  - pathlib2==2.3.0
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.15
  - ptyprocess==0.5.2
  - pyface==5.1.0
  - pygments==2.2.0
  - pymcubes==0.0.6
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - pytz==2017.2
  - pyvtk==0.5.18
  - scandir==1.5
  - simplegeneric==0.8.1
  - six==1.10.0
  - sympy==1.1.1
  - tqdm==4.15.0
  - traitlets==4.3.2
  - traits==4.6.0
  - traitsui==5.1.0
  - wcwidth==0.1.7
prefix: ~/anaconda/envs/img_pipe_py2

